const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const api = path => fetch(`/api/${path}`).then(response => { if (!response.ok) throw new Error("Não foi possível carregar o conteúdo."); return response.json(); });
let data = {};
function waLink(message="Olá, gostaria de obter mais informações sobre a Lumax.") { const value=String(data.settings?.whatsapp||"").replace(/\D/g,""); return value.length>=8?`https://wa.me/${value}?text=${encodeURIComponent(message)}`:"#contactos"; }
function setText(id,value){document.getElementById(id).textContent=value||""}
function setupContact(){const s=data.settings, phone=String(s.phone||"").replace(/\D/g,""); document.querySelectorAll("[data-whatsapp]").forEach(link=>{link.href=waLink(link.dataset.message);if(String(s.whatsapp||"").replace(/\D/g,"").length>=8){link.target="_blank";link.rel="noopener"}}); const quick=document.getElementById("phoneQuick");quick.href=phone.length>=8?`tel:${phone}`:"#contactos"; document.getElementById("contactPhone").innerHTML=phone?`<a href="tel:${phone}">${escapeHtml(s.phone)}</a>`: "";document.getElementById("contactEmail").innerHTML=s.email?`<a href="mailto:${escapeHtml(s.email)}">${escapeHtml(s.email)}</a>`:"";setText("contactAddress",s.address);["facebookLink","footerFacebook"].forEach(id=>document.getElementById(id).href=s.facebook||"#");const map=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address||"")}`;["mapsQuick","mapsLink"].forEach(id=>document.getElementById(id).href=map)}
function render(){const s=data.settings;setText("trustEyebrow",s.trust_eyebrow);setText("trustTitle",s.trust_title);setText("trustSubtitle",s.trust_subtitle);setText("servicesEyebrow",s.services_eyebrow);setText("servicesTitle",s.services_title);setText("propertiesEyebrow",s.properties_eyebrow);setText("propertiesTitle",s.properties_title);setText("propertiesNotice",s.properties_notice);setText("faqEyebrow",s.faq_eyebrow);setText("faqTitle",s.faq_title);
document.getElementById("trustGrid").innerHTML=data.trust_steps.map(step=>`<article class="card feature"><span class="number">${String(step.order||0).padStart(2,"0")}</span><h3>${escapeHtml(step.title)}</h3><p>${escapeHtml(step.description)}</p></article>`).join("");
document.getElementById("servicesGrid").innerHTML=data.services.map((service,index)=>`<article class="card"><div class="service-icon">${String(index+1).padStart(2,"0")}</div><h3>${escapeHtml(service.title)}</h3><p>${escapeHtml(service.desc)}</p><button class="text-btn service-more" data-id="${service.id}">Saber mais →</button></article>`).join("");
document.getElementById("propertiesGrid").innerHTML=data.properties.map(property=>`<article class="card property"><div class="property-img" style="background-image:url('${encodeURI(property.image||"")}')"></div><div class="property-body"><h3>${escapeHtml(property.title)}</h3><div class="property-meta"><span>${escapeHtml(property.location||"Localização sob consulta")}</span><span>${escapeHtml(property.type||"Imóvel")}</span></div><p class="price">${escapeHtml(property.price||"Preço sob consulta")}</p><div class="card-actions"><button class="btn btn-outline small-btn details" data-id="${property.id}">Saber mais</button><a class="btn btn-gold small-btn" href="${waLink(`Olá, gostaria de obter informações sobre o imóvel: ${property.title}`)}">Contactar</a></div></div></article>`).join("");
document.getElementById("faqList").innerHTML=data.faq.map(item=>`<details><summary>${escapeHtml(item.question)}</summary><p>${escapeHtml(item.answer)}</p></details>`).join("");
document.getElementById("postsGrid").innerHTML=data.posts.map(post=>`<article class="card"><p class="eyebrow">${escapeHtml(post.category)}</p><h3>${escapeHtml(post.title)}</h3><p>${escapeHtml(post.text)}</p></article>`).join("");document.getElementById("galleryGrid").innerHTML=data.gallery.map(item=>`<article class="card property"><div class="property-img" style="background-image:url('${encodeURI(item.image||"")}')"></div>${item.title?`<div class="property-body"><h3>${escapeHtml(item.title)}</h3></div>`:""}</article>`).join("");}
const modal=document.getElementById("modal"), modalContent=document.getElementById("modalContent");function openModal(html){modalContent.innerHTML=html;modal.classList.add("open");modal.setAttribute("aria-hidden","false")}function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}document.querySelector(".close").onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
document.addEventListener("click",event=>{const service=event.target.closest(".service-more"), property=event.target.closest(".details");if(service){const x=data.services.find(item=>item.id===service.dataset.id);openModal(`<div class="modal-service"><p class="eyebrow">SERVIÇO LUMAX</p><h2>${escapeHtml(x.title)}</h2><p>${escapeHtml(x.desc)}</p><a class="btn btn-gold" href="${waLink(`Olá, gostaria de saber mais sobre o serviço: ${x.title}`)}">Fale connosco</a></div>`)}if(property){const x=data.properties.find(item=>item.id===property.dataset.id);openModal(`<p class="eyebrow">IMÓVEL EM DESTAQUE</p><h2>${escapeHtml(x.title)}</h2><p><strong>Localização:</strong> ${escapeHtml(x.location)}</p><p><strong>Tipo:</strong> ${escapeHtml(x.type)}</p><p><strong>Preço:</strong> ${escapeHtml(x.price)}</p><p>${escapeHtml(x.description)}</p>`)}});
const header=document.querySelector(".header"),menu=document.querySelector(".menu-btn");menu.onclick=()=>{const open=header.classList.toggle("open");menu.setAttribute("aria-expanded",String(open))};document.querySelectorAll("nav a").forEach(link=>link.onclick=()=>{header.classList.remove("open");menu.setAttribute("aria-expanded","false")});
document.getElementById("bookingForm").onsubmit=event=>{event.preventDefault();const f=new FormData(event.target),msg=`Olá, gostaria de agendar uma visita.\n\nNome: ${f.get("nome")}\nTelefone: ${f.get("telefone")}\nImóvel: ${f.get("imovel")||"Não informado"}`;window.open(waLink(msg),"_blank","noopener")};document.querySelectorAll("[data-modal]").forEach(button=>button.onclick=()=>openModal("<h2>Política de Privacidade</h2><p>Este site não guarda dados de formulário. Os pedidos são preparados para envio pelo WhatsApp.</p>"));
Promise.all(["settings","trust_steps","services","properties","posts","gallery","faq"].map(api)).then(values=>{[data.settings,data.trust_steps,data.services,data.properties,data.posts,data.gallery,data.faq]=values;setupContact();render()}).catch(error=>console.error(error));
