const contentDefaults = {
  settings: { phone: "927 729 874", whatsapp: "244927729874", email: "mplumax1@gmail.com", address: "Bairro Valodia, Moçâmedes, Província do Namibe, Angola", facebook: "https://www.facebook.com/profile.php?id=61591040086745", trust_eyebrow: "A FORMA LUMAX", trust_title: "Confiança para decidir com tranquilidade.", trust_subtitle: "Uma abordagem próxima e profissional para que cada processo tenha um caminho mais claro.", services_eyebrow: "SOLUÇÕES IMOBILIÁRIAS", services_title: "Serviços pensados para si.", properties_eyebrow: "SELEÇÃO LUMAX", properties_title: "Imóveis em destaque.", properties_notice: "Confirme connosco a disponibilidade e as condições atuais.", faq_eyebrow: "DÚVIDAS FREQUENTES", faq_title: "Como podemos ajudar?" },
  trust_steps: [{ order: 1, title: "Escuta atenta", description: "Começamos por compreender as suas necessidades, prioridades e objetivos." }, { order: 2, title: "Informação clara", description: "Orientação direta para apoiar escolhas mais informadas em cada etapa." }, { order: 3, title: "Acompanhamento", description: "Presença próxima desde a procura até à concretização do seu próximo passo." }, { order: 4, title: "Relação de confiança", description: "Uma experiência imobiliária feita com rigor, discrição e transparência." }],
  services: [{ title: "Compra", desc: "Apoio na procura e na tomada de decisão para encontrar o imóvel certo para si." }, { title: "Venda", desc: "Acompanhamento na apresentação e divulgação do seu imóvel com uma comunicação cuidada." }, { title: "Arrendamento", desc: "Orientação para encontrar opções de arrendamento adequadas às suas necessidades." }],
  faq: [{ question: "Que documentos preciso para vender um imóvel?", answer: "Os documentos podem variar conforme o imóvel e o processo. Fale com a Lumax para orientação sobre o seu caso." }, { question: "A Lumax cobra comissão?", answer: "As condições comerciais devem ser confirmadas diretamente com a Lumax antes de qualquer contratação." }],
  properties: [], posts: [], gallery: []
};
const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
const api = path => fetch(`/api/${path}`).then(response => { if (!response.ok) throw new Error(`${path}: ${response.status}`); return response.json(); });
const data = structuredClone(contentDefaults);
const byId = id => document.getElementById(id);
const setText = (id, value, fallback = "") => { byId(id).textContent = String(value || fallback); };
function waLink(message = "Olá, gostaria de obter mais informações sobre a LUMAX.") { const number = String(data.settings.whatsapp || "").replace(/\D/g, ""); return number.length >= 8 ? `https://wa.me/${number}?text=${encodeURIComponent(message)}` : "#contactos"; }
function empty(container, message) { container.innerHTML = `<p class="content-empty">${escapeHtml(message)}</p>`; }
function setupContact() { const s = data.settings, phone = String(s.phone || "").replace(/\D/g, ""); document.querySelectorAll("[data-whatsapp]").forEach(link => { link.href = waLink(link.dataset.message); if (link.href !== "#contactos") { link.target = "_blank"; link.rel = "noopener"; } }); const quick = byId("phoneQuick"); quick.href = phone.length >= 8 ? `tel:${phone}` : "#contactos"; setText("contactPhone", s.phone, contentDefaults.settings.phone); byId("contactPhone").innerHTML = `<a href="${quick.href}">${escapeHtml(s.phone || contentDefaults.settings.phone)}</a>`; byId("contactEmail").innerHTML = `<a href="mailto:${escapeHtml(s.email || contentDefaults.settings.email)}">${escapeHtml(s.email || contentDefaults.settings.email)}</a>`; setText("contactAddress", s.address, contentDefaults.settings.address); ["facebookLink", "footerFacebook"].forEach(id => byId(id).href = s.facebook || "#"); const map = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address || contentDefaults.settings.address)}`; ["mapsQuick", "mapsLink"].forEach(id => byId(id).href = map); }
function render() { const s = data.settings; [["trustEyebrow", "trust_eyebrow"], ["trustTitle", "trust_title"], ["trustSubtitle", "trust_subtitle"], ["servicesEyebrow", "services_eyebrow"], ["servicesTitle", "services_title"], ["propertiesEyebrow", "properties_eyebrow"], ["propertiesTitle", "properties_title"], ["propertiesNotice", "properties_notice"], ["faqEyebrow", "faq_eyebrow"], ["faqTitle", "faq_title"]].forEach(([id, key]) => setText(id, s[key], contentDefaults.settings[key]));
  byId("trustGrid").innerHTML = data.trust_steps.map(step => `<article class="card feature"><span class="number">${String(step.order || 0).padStart(2, "0")}</span><h3>${escapeHtml(step.title)}</h3><p>${escapeHtml(step.description)}</p></article>`).join("");
  byId("servicesGrid").innerHTML = data.services.map((service, index) => `<article class="card"><div class="service-icon">${String(index + 1).padStart(2, "0")}</div><h3>${escapeHtml(service.title)}</h3><p>${escapeHtml(service.desc)}</p><button class="text-btn service-more" data-id="${escapeHtml(service.id || index)}">Saber mais →</button></article>`).join("");
  const properties = byId("propertiesGrid"); if (!data.properties.length) empty(properties, "De momento não existem imóveis em destaque. Contacte-nos para conhecer as opções disponíveis."); else properties.innerHTML = data.properties.map((property, index) => `<article class="card property"><div class="property-img"${property.image ? ` style="background-image:url('${encodeURI(property.image)}')"` : ""} role="img" aria-label="${escapeHtml(property.title)}">${property.image ? "" : "Fotografia indisponível"}</div><div class="property-body"><h3>${escapeHtml(property.title || "Imóvel disponível")}</h3><div class="property-meta"><span>${escapeHtml(property.location || "Localização sob consulta")}</span><span>${escapeHtml(property.type || "Imóvel")}</span></div><p class="price">${escapeHtml(property.price || "Preço sob consulta")}</p><div class="card-actions"><button class="btn btn-outline small-btn details" data-id="${escapeHtml(property.id || index)}">Saber mais</button><a class="btn btn-gold small-btn" target="_blank" rel="noopener" href="${waLink(`Olá, gostaria de obter informações sobre o imóvel: ${property.title}`)}">Contactar</a></div></div></article>`).join("");
  byId("faqList").innerHTML = data.faq.map(item => `<details><summary>${escapeHtml(item.question)}</summary><p>${escapeHtml(item.answer)}</p></details>`).join("");
  const posts = byId("postsGrid"); data.posts.length ? posts.innerHTML = data.posts.map(post => `<article class="card"><p class="eyebrow">${escapeHtml(post.category)}</p><h3>${escapeHtml(post.title)}</h3><p>${escapeHtml(post.text)}</p></article>`).join("") : empty(posts, "Novidades em breve.");
  const gallery = byId("galleryGrid"); data.gallery.length ? gallery.innerHTML = data.gallery.map((item, index) => `<figure class="gallery-item"><img src="${encodeURI(item.image || "")}" alt="${escapeHtml(item.title || `Imagem da galeria ${index + 1}`)}" loading="lazy"><figcaption>${escapeHtml(item.title || "Lumax")}</figcaption></figure>`).join("") : empty(gallery, "A galeria será atualizada em breve.");
}
const modal = byId("modal"), modalContent = byId("modalContent"); function openModal(html) { modalContent.innerHTML = html; modal.classList.add("open"); modal.setAttribute("aria-hidden", "false"); } function closeModal() { modal.classList.remove("open"); modal.setAttribute("aria-hidden", "true"); } document.querySelector(".close").onclick = closeModal; modal.onclick = event => { if (event.target === modal) closeModal(); };
document.addEventListener("click", event => { const service = event.target.closest(".service-more"), property = event.target.closest(".details"); if (service) { const x = data.services.find(item => String(item.id || data.services.indexOf(item)) === service.dataset.id); if (x) openModal(`<div class="modal-service"><h2>${escapeHtml(x.title)}</h2><p>${escapeHtml(x.desc)}</p><a class="btn btn-gold" target="_blank" rel="noopener" href="${waLink(`Olá, gostaria de saber mais sobre o serviço: ${x.title}`)}">Fale connosco</a></div>`); } if (property) { const x = data.properties.find((item, index) => String(item.id || index) === property.dataset.id); if (x) openModal(`<h2>${escapeHtml(x.title)}</h2><p><strong>Localização:</strong> ${escapeHtml(x.location || "Sob consulta")}</p><p><strong>Tipo:</strong> ${escapeHtml(x.type || "Sob consulta")}</p><p><strong>Preço:</strong> ${escapeHtml(x.price || "Sob consulta")}</p><p>${escapeHtml(x.description)}</p>`); } });
const header = document.querySelector(".header"), menu = document.querySelector(".menu-btn"); menu.onclick = () => { const open = header.classList.toggle("open"); menu.setAttribute("aria-expanded", String(open)); }; document.querySelectorAll("nav a").forEach(link => link.onclick = () => { header.classList.remove("open"); menu.setAttribute("aria-expanded", "false"); });
byId("bookingForm").onsubmit = event => { event.preventDefault(); const f = new FormData(event.target); window.open(waLink(`Olá, gostaria de agendar uma visita.\n\nNome: ${f.get("nome")}\nTelefone: ${f.get("telefone")}\nImóvel: ${f.get("imovel") || "Não informado"}`), "_blank", "noopener"); }; document.querySelectorAll("[data-modal]").forEach(button => button.onclick = () => openModal("<h2>Política de Privacidade</h2><p>Este site não guarda dados de formulário. Os pedidos são preparados para envio pelo WhatsApp.</p>"));
Promise.allSettled(Object.keys(contentDefaults).map(key => api(key).then(value => [key, value]))).then(results => { results.forEach(result => { if (result.status === "fulfilled") { const [key, value] = result.value; if (key === "settings") data.settings = { ...contentDefaults.settings, ...(value || {}) }; else if (Array.isArray(value) && (value.length || !["trust_steps", "services", "faq"].includes(key))) data[key] = value; } else console.warn("Conteúdo indisponível; foi usado conteúdo seguro.", result.reason); }); setupContact(); render(); });
