const defaults={settings:{phone:"927 729 874",whatsapp:"244927729874",email:"mplumax1@gmail.com",address:"Namibe, Angola. Atua também em Moçâmedes e Cacuaco/Luanda.",facebook:"https://www.facebook.com/Lumaxmobiliaria-mp"},services:[{title:"Compra",desc:"Apoio na procura e negociação do imóvel adequado às suas necessidades."},{title:"Venda",desc:"Apoio na apresentação e divulgação do seu imóvel."},{title:"Arrendamento",desc:"Orientação para encontrar soluções de arrendamento."},{title:"Gestão de Património",desc:"Acompanhamento de imóveis e património conforme as necessidades acordadas."},{title:"Consultoria Imobiliária",desc:"Informação e orientação para apoiar decisões imobiliárias."}],properties:[{title:"Imóvel disponível sob consulta",type:"Residencial",location:"Namibe",price:"Sob consulta",description:"Contacte a LUMAX para confirmar disponibilidade e condições.",image:""},{title:"Oportunidade imobiliária",type:"Imóvel",location:"Área de atuação da LUMAX",price:"Sob consulta",description:"Exemplo de imóvel demonstrativo editável no painel administrativo.",image:""}],posts:[{category:"Novidades",title:"Acompanhe as oportunidades da LUMAX",text:"Consulte-nos para conhecer imóveis e soluções disponíveis."},{category:"Dicas",title:"Antes de escolher um imóvel",text:"Defina localização, necessidades e objetivos do seu investimento."}],gallery:[]};
settings:{phone:"927729874",whatsapp:"927729874",email:"mplumax1@gmail.com",address:"Bairro Valodia, Moçâmedes, Província do Namibe, Angola",facebook:"https://www.facebook.com/profile.php?id=61591040086745"},
const data={};Object.keys(defaults).forEach(k=>data[k]=getData(k));
const s=data.settings;
function waLink(msg="Olá, gostaria de obter mais informações sobre a LUMAX."){return`https://wa.me/${String(s.whatsapp).replace(/\D/g,"")}?text=${encodeURIComponent(msg)}`}
document.querySelectorAll("[data-whatsapp]").forEach(a=>{a.href=waLink(a.dataset.message||undefined);a.target="_blank";a.rel="noopener"});
document.getElementById("phoneQuick").href="tel:"+s.phone.replace(/\D/g,"");document.getElementById("phoneQuick").textContent="☎ Ligar agora";
["mapsQuick","mapsLink"].forEach(id=>document.getElementById(id).href="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent("Namibe, Angola"));
document.getElementById("contactPhone").innerHTML=`<a href="tel:${s.phone.replace(/\D/g,"")}">${s.phone}</a>`;
document.getElementById("contactEmail").innerHTML=`<a href="mailto:${s.email}">${s.email}</a>`;
document.getElementById("contactAddress").textContent=s.address;document.getElementById("facebookLink").href=s.facebook;
document.querySelector(".menu-btn").onclick=()=>document.querySelector(".header").classList.toggle("open");
const modal=document.getElementById("modal"),mc=document.getElementById("modalContent");function openModal(html){mc.innerHTML=html;modal.classList.add("open");modal.setAttribute("aria-hidden","false")}function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}document.querySelector(".close").onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
document.getElementById("servicesGrid").innerHTML=data.services.map((x,i)=>`<article class="card"><div class="service-icon">⌂</div><h3>${x.title}</h3><p>${x.desc}</p><button class="text-btn service-more" data-i="${i}">Saber mais →</button></article>`).join("");
document.addEventListener("click",e=>{if(e.target.matches(".service-more")){let x=data.services[e.target.dataset.i];openModal(`<div class="modal-service"><h2>${x.title}</h2><p>${x.desc}</p><p>Para conhecer as condições e o funcionamento deste serviço, fale diretamente com a LUMAX.</p><a class="btn btn-gold" target="_blank" href="${waLink("Olá, gostaria de saber mais sobre o serviço: "+x.title)}">Falar no WhatsApp</a></div>`)}});

function renderProperties(){let g=document.getElementById("propertiesGrid");g.innerHTML=data.properties.map((p,i)=>`<article class="card property"><div class="property-img" style="${p.image?`background-image:url('${p.image}')`:''}" role="img" aria-label="${p.title}">${!p.image?"Imagem ilustrativa":""}</div><div class="property-body"><h3>${p.title}</h3><div class="property-meta"><span>${p.location||""}</span><span>${p.type||""}</span></div><p class="price">${p.price||"Sob consulta"}</p><div class="card-actions"><button class="btn dark small-btn details" data-i="${i}">Ver detalhes</button><a class="btn btn-gold small-btn" target="_blank" href="${waLink("Olá, gostaria de obter informações sobre o imóvel: "+p.title)}">Perguntar no WhatsApp</a></div></div></article>`).join("")}
renderProperties();document.addEventListener("click",e=>{if(e.target.matches(".details")){let p=data.properties[e.target.dataset.i];openModal(`<h2>${p.title}</h2><p><strong>Localização:</strong> ${p.location||"Sob consulta"}</p><p><strong>Tipo:</strong> ${p.type||"Sob consulta"}</p><p><strong>Preço:</strong> ${p.price||"Sob consulta"}</p><p>${p.description||""}</p><a class="btn btn-gold" target="_blank" href="${waLink("Olá, gostaria de saber mais sobre: "+p.title)}">Perguntar no WhatsApp</a>`)}});

let active="Todos";function renderPosts(){document.getElementById("postsGrid").innerHTML=data.posts.filter(p=>active==="Todos"||p.category===active).map(p=>`<article class="card"><p class="post-cat">${p.category}</p><h3>${p.title}</h3><p>${p.text}</p></article>`).join("")||"<p>Nenhuma publicação nesta categoria.</p>"}renderPosts();document.querySelectorAll("#postFilters button").forEach(b=>b.onclick=()=>{active=b.dataset.filter;document.querySelectorAll("#postFilters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPosts()});
let fallback=["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80"];let gallery=data.gallery.length?data.gallery.map(x=>x.image):fallback;document.getElementById("galleryGrid").innerHTML=gallery.map((u,i)=>`<figure data-src="${u}"><img src="${u}" alt="Imóvel ou interior ${i+1}" loading="lazy"><figcaption>Imagem ${data.gallery.length?"da galeria":"ilustrativa"}</figcaption></figure>`).join("");document.querySelectorAll("#galleryGrid figure").forEach(f=>f.onclick=()=>openModal(`<img src="${f.dataset.src}" alt="Imagem ampliada" style="width:100%;height:auto;border-radius:8px">`));
document.getElementById("bookingForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),msg=`Olá, gostaria de agendar uma visita.%0A%0ANome: ${f.get("nome")}%0ATelefone: ${f.get("telefone")}%0AImóvel: ${f.get("imovel")||"Não informado"}%0AData/Hora: ${f.get("data")||"A combinar"}%0AMensagem: ${f.get("mensagem")||"-"}`;window.open(`https://wa.me/${s.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(decodeURIComponent(msg))}`,"_blank")};
const faq=[["Que documentos preciso para vender um imóvel?","Os documentos necessários podem variar conforme o imóvel e o processo. Contacte a LUMAX para orientação sobre o seu caso."],["A LUMAX cobra comissão?","As condições comerciais devem ser confirmadas diretamente com a LUMAX antes de qualquer contratação."],["Como funciona a gestão de património?","O serviço pode envolver diferentes necessidades de acompanhamento. Consulte a empresa para conhecer o funcionamento aplicável ao seu património."],["Como agendo uma visita?","Pode preencher o formulário desta página ou falar diretamente pelo WhatsApp."]];document.getElementById("faqList").innerHTML=faq.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join("");
document.querySelectorAll("[data-modal]").forEach(b=>b.onclick=()=>openModal(b.dataset.modal==="privacy"?`<h2>Política de Privacidade</h2><p>Este site demonstrativo não deve guardar dados sensíveis de clientes. Os formulários desta versão apenas encaminham o utilizador para o WhatsApp.</p>`:`<h2>Termos de Uso</h2><p>As informações apresentadas devem ser confirmadas diretamente com a LUMAX. A disponibilidade e condições dos imóveis podem ser alteradas.</p>`));