services:
  - type: web
    name: lumax
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
