services:
  - type: web
    name: lumax
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
